bin: run_vm: Add /dev/cgroup/memory as a fallback path for the memcg mount
Signed-off-by: Sean Christopherson <seanjc@google.com>

diff --git a/bin/run_vm b/bin/run_vm
--- a/bin/run_vm
+++ b/bin/run_vm
@@ -42,8 +42,11 @@ fi
 
 cgroup=$(grep ^cgroup /proc/mounts | grep memory | grep -v root | cut -f 2 -d ' ')
 if [[ ! -d $cgroup ]]; then
-    printf "Cannot find memory cgroup mount point, got '$cgroup'\n"
-    exit 1
+    cgroup="/dev/cgroup/memory"
+    if [[ ! -d $cgroup ]]; then
+        printf "Cannot find memory cgroup mount point, got '$cgroup'\n"
+        exit 1
+    fi
 fi
 cgroup="$cgroup/vm"
 if [[ ! -d $cgroup ]]; then
